# 默认配置文件，部分参数可以修改，但注意是否正确，否则报错
global:
  map_path: &map_path "/home/grifcc/xjy/new/ObjectLocation_cpp_test/data/plane_map_test.npy" #可更换地图
  max_queue_length: &max_queue_length 99999

  time_slice: &time_slice 1 # 时间线融合, 可以调整, 单位ms

  del_easting: &del_easting 508129.51379 # 地图相对于UTM坐标系的x轴偏移
  del_northing: &del_northing 12663298.75058 # 地图相对于UTM坐标系的y轴偏移
  del_uav1_height: &del_uav1_height 0.0 # 无人机1的IMU高度偏移
  del_uav2_height: &del_uav2_height 20.0 # 无人机2的IMU高度偏移

  sigma_a: &sigma_a 0.1 # 无人机加速度噪声标准差
  output_ip: &output_ip "192.168.13.1"
  output_port: &output_port 8888
  output_interface: &output_interface "enp4s0f1"

input:

  stage1:
    idx: 1
    name: "ZeroMQ"
    args:
      endpoint1: "ipc:///tmp/zmq-test0"
      endpoint2: "ipc:///tmp/zmq-test1"
      topic: "land_stream"


  stage2:
    idx: 2
    name: "DataConvert"
    args:
      del_easting: *del_easting
      del_northing: *del_northing
      del_uav1_height: *del_uav1_height
      del_uav2_height: *del_uav2_height
      max_queue_length: *max_queue_length


pipeline:

  stage1:
    idx: 1
    parallel: 1
    name: "TimeFilter"
    args:
      time_slice: *time_slice
      max_queue_length: *max_queue_length


  stage2:
    idx: 2
    parallel: 1  # 并行数，不建议太大
    name: "EstiPosition"
    args:
      is_multi_map : False
      map_path: *map_path  # 多尺度地图时pkl文件，否则是obj文件
      default_height: -3.5 #默认平面
      order: "szxy"
      enable_reloaction: True
      max_queue_length: *max_queue_length


  stage3:
    idx: 3
    parallel: 1
    name: "PkgArrange"
    args:
      max_queue_length: *max_queue_length


  stage4:
    idx: 4
    name: "SpatialFilter"
    parallel: 1
    args:
      time_slice: *time_slice
      distance_threshold: 10.0 #多机融合距离阈值
      max_map: 100
      max_queue_length: *max_queue_length


  stage5:
    idx: 5
    name: "RTKDifference"
    parallel: 1
    args:
      time_slice: *time_slice
      class_1: 1
      x1: 20.0
      y1: 30.0
      class_2: 2
      x2: -10.0
      y2: 10.0
      max_queue_length: *max_queue_length

output:

  stage1:
    idx: 1
    name: "Fusion"
    args:
      time_slice: *time_slice
      max_queue_length: *max_queue_length

  stage2:
    idx: 2
    name: "Kalman"
    args:
      time_slice: 1
      sigma_a: *sigma_a
      max_queue_length: *max_queue_length

  stage3:
    idx: 3
    name: "UdpOutput"
    args:
      ip: *output_ip
      port: *output_port
      interface: *output_interface