# 默认配置文件，部分参数可以修改，但注意是否正确，否则报错
global:
  map_path: &map_path "/home/xjy/code/location_Map/test_1/data/mesh_triangles.npy" #可更换地图
 # multi_map_path: &multi_map_path "data/map/yumen/Tile_geo.pkl" #暂未实现
  time_slice: &time_slice 0 # 时间线融合, 可以调整, 单位ms
  enable_reloaction: &enable_reloaction False
  order: &order "rzyx" # 固定参数
  max_queue_length: &max_queue_length 1000

input:

  stage1:
    idx: 1
    name: "DataConvert"
    args:
      max_queue_length: *max_queue_length

pipeline:

  stage1:
    idx: 1
    parallel: 1
    name: "TimeFilter"
    args:
      time_slice: *time_slice
      max_queue_length: *max_queue_length

  # stage2:
  #   idx: 2
  #   parallel: 4  # 并行数，根据机器性能调整
  #   name: "EstiPosition"
  #   args:
  #     is_multi_map : True
  #     map_path: *multi_map_path # 多尺度地图时pkl文件，否则是obj文件
  #     default_height: -3.5  #默认平面
  #     order: *order
  #     enable_reloaction: *enable_reloaction
  #     max_queue_length: *max_queue_length
  #     multi_num : 2 # 多尺度选项：一共几层地图
  #     downSampled_scale : [0.2, 0.1] # 每层地图相对于原始地图的下采样倍数
  #     split_scale : [[10, 10], [5, 5]] # 每层地图分为多少块
  #     block_num : 1 # 找不到的情况下，向周围几个block遍历
  #     overlap_x_scale : 0.1 # 切分的x重叠率
  #     overlap_y_scale : 0.1 # 切分的y重叠率


  stage2:
    idx: 2
    parallel: 4  # 并行数，不建议太大
    name: "EstiPosition"
    args:
      is_multi_map : False
      map_path: *map_path  # 多尺度地图时pkl文件，否则是obj文件
      default_height: -3.5 #默认平面
      order: *order
      enable_reloaction: *enable_reloaction
      max_queue_length: *max_queue_length


  stage3:
    idx: 3
    name: "SpatialFilter"
    parallel: 1
    args:
      time_slice: *time_slice
      distance_threshold: 10.0 #多机融合距离阈值
      max_map: 100
      max_queue_length: *max_queue_length

  stage4:
    idx: 4
    name: "Output"
    parallel: 1
    args:
      time_slice: *time_slice
      max_queue_length: *max_queue_length